version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: "-c /etc/nats/nats.conf"
    networks: ["nats"]

  nats-1:
    image: nats
    ports:
      - "8223:8222"
      - "4223:4222"
      - "6223:6222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: "-c /etc/nats/nats.conf"
    networks: ["nats"]
    depends_on: ["nats"]

  nats-2:
    image: nats
    ports:
      - "8224:8222"
      - "4224:4222"
      - "6224:6222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: "-c /etc/nats/nats.conf"
    networks: ["nats"]
    depends_on: ["nats"]

  producer:
    build: .
    ports:
      - "5001:5001"
    environment:
      - API_PORT=5001
      - USER_NATS=ruser
      - PASS_NATS=T0pS3cr3t
      - CHANNEL_NATS=users
      - SERVER_NATS_URL_1=nats://nats:4222
      - SERVER_NATS_URL_2=nats://nats-1:4223
      - SERVER_NATS_URL_3=nats://nats-2:4224
    depends_on: ["nats"]
    command: ["npm", "run", "producer"]
    networks: ["nats"]

  consumer-1:
    build: .
    container_name: consumer-1
    environment:
      - USER_NATS=ruser
      - PASS_NATS=T0pS3cr3t
      - CHANNEL_NATS=users      
      - SERVER_NATS_URL_1=nats://nats:4222
      - SERVER_NATS_URL_2=nats://nats-1:4223
      - SERVER_NATS_URL_3=nats://nats-2:4224
    depends_on: ["nats"]
    command: ["npm", "run", "consumer:1"]
    networks: ["nats"]

  consumer-2:
    build: .
    container_name: consumer-2
    environment:
      - USER_NATS=ruser
      - PASS_NATS=T0pS3cr3t
      - CHANNEL_NATS=users      
      - SERVER_NATS_URL_1=nats://nats:4222
      - SERVER_NATS_URL_2=nats://nats-1:4223
      - SERVER_NATS_URL_3=nats://nats-2:4224
    depends_on: ["nats"]
    command: ["npm", "run", "consumer:2"]
    networks: ["nats"]

  consumer-3:
    build: .
    container_name: consumer-3
    environment:
      - USER_NATS=ruser
      - PASS_NATS=T0pS3cr3t
      - CHANNEL_NATS=users      
      - SERVER_NATS_URL_1=nats://nats:4222
      - SERVER_NATS_URL_2=nats://nats-1:4223
      - SERVER_NATS_URL_3=nats://nats-2:4224
    depends_on: ["nats"]
    command: ["npm", "run", "consumer:3"]
    networks: ["nats"]

networks:
  nats:
    name: nats
